name: "YAML file linter"
description: "Lint a YAML file in your project"
inputs:
  name:
    required: false
    description: the person/thing you want to greet
    default: World
outputs:
  phrase:
    description: output message

runs:
  using: 'docker'
  image: 'Dockerfile'