on:
  pull_request:
    types: [review_requested]
jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    steps:
      - env:
          requested_reviewers: ${{ toJson(github.event.pull_request.requested_reviewers) }}
        run: |
          echo "$requested_reviewers"
          reviewers_count=$(echo $requested_reviewers | jq '. | length')
          echo "::set-output name=result::$reviewers_count"
        id: reviewers_count

      - run:
          echo ${{ steps.reviewers_count.outputs.result }}
          echo ${{ steps.reviewers_count.outputs.result == 1 }}

      - if: steps.reviewers_count.outputs.result == 1
        run: echo "a"

      - if: steps.reviewers_count.outputs.result >= 1
        run: echo "b"
