on:
  pull_request:
#    types: [review_requested]
jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    #    if: ${{ github.event.requested_team.name == 'octo-team'}}
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v4
      - uses: ./
#        with:
#          reviewers: '${{github.sha}}'

#      - run: |
#          for reviewer in ${{ github.event.pull_request.requested_reviewers }}; do
#            echo "$reviewer"
#          done
#      - run: echo  ${{ github.event.pull_request.requested_reviewers }}
